name: Docker
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:      
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: glebz1
          password: V2kVba2gjHdas-6
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: glebz1/killerjoke623:latest
